"""Declarative base, shared column types and mixins."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import BigInteger, DateTime, Integer, MetaData, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON

#: Explicit naming convention so Alembic emits stable, human-readable names for
#: indexes and constraints instead of database-generated ones. Without this,
#: autogenerated downgrades cannot reliably drop what they created.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

#: JSONB on PostgreSQL (indexable, binary) and plain JSON elsewhere, so the same
#: models run against SQLite in the test suite.
JSONType = JSON().with_variant(JSONB(), "postgresql")


class Base(DeclarativeBase):
    """Base class for every ORM model.

    ``eager_defaults`` matters more than it looks. Server-generated values —
    :class:`TimestampMixin`'s ``server_default`` and ``onupdate`` — are unknown to
    the ORM after a flush, so by default the attribute is left expired and the
    *next read of it* performs the fetch. Under asyncio that read is synchronous
    IO from a non-greenlet context and raises ``MissingGreenlet``, turning an
    innocent ``user.updated_at`` into a crash far from the code that caused it.

    Fetching eagerly closes that trap for every model at once. On PostgreSQL and
    SQLite the values come back via RETURNING on the original statement, so this
    costs no extra round-trip.
    """

    __mapper_args__ = {"eager_defaults": True}  # noqa: RUF012 - SQLAlchemy API

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy API expects a plain dict
        dict[str, Any]: JSONType,
        list[str]: JSONType,
    }

    def __repr__(self) -> str:
        pk = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


class IntPrimaryKeyMixin:
    """Surrogate integer primary key."""

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)


class OwnerMixin:
    """Ties a row to the Telegram user who owns it.

    The bot is multi-tenant: anyone can connect their own channel and run their
    own schedule over the shared question bank. Every row that belongs to one
    person rather than to the installation carries this column, and every query
    for such rows filters on it — an unscoped query would leak one user's
    channels, progress or settings into another's panel.

    Stored as the raw Telegram id rather than a foreign key to ``bot_users``, so
    a row survives its owner being purged and no lookup is needed to scope a
    query.
    """

    owner_id: Mapped[int] = mapped_column(
        BigInteger, nullable=False, index=True, doc="Telegram id of the owning user"
    )


class TimestampMixin:
    """``created_at`` / ``updated_at`` maintained by the database.

    Defaults are server-side so rows inserted by a migration, a manual SQL fix or
    a restore all carry sane timestamps.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


#: Telegram ids exceed 32-bit range; always store them as BIGINT.
TelegramId = BigInteger
